version: '3'
services:
  api:
    container_name: one_account_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rails
    labels:
      repository: git@github.com:maikondouglas/one_account.git
    volumes:
      - ./:/current
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: bin/rails server -b '0.0.0.0'

  db:
    image: postgres:12
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
