default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: maikondouglas
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: one_account_development

test:
  <<: *default
  database: one_account_test
