name: Pipeline

on: [push]

jobs:
  build:
    name: Run Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Rubocop
        run: |
          bundle exec rubocop

      - name: RSpec
        if: ${{ job.status == 'success' }}
        run: |
          bundle exec rspec

      - name: Run RSpec and generate coverage report
        if: ${{ job.status == 'success' }}
        env:
          CI: true
        run: |
          bundle exec rspec
          mkdir -p coverage
          mv coverage/index.html coverage/index_last_run.html
          mv coverage/.last_run.json coverage/last_run.json

      - name: Archive coverage artifacts
        if: ${{ job.status == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-artifacts
          path: coverage

